DROP TABLE CUSTOMER_LOYALTY CASCADE CONSTRAINTS;
DROP TABLE FAVORITES CASCADE CONSTRAINTS;
DROP TABLE DAMAGE_REPORT CASCADE CONSTRAINTS;
DROP TABLE RENTALS CASCADE CONSTRAINTS;
DROP TABLE RESERVATIONS CASCADE CONSTRAINTS;
DROP TABLE VEHICLE_MAINTENANCE CASCADE CONSTRAINTS;
DROP TABLE DRIVER_LICENSES CASCADE CONSTRAINTS;
DROP TABLE RENTAL_CUSTOMERS CASCADE CONSTRAINTS;
DROP TABLE PROCUREMENT_RECORDS CASCADE CONSTRAINTS;
DROP TABLE LOYALTY_TIERS CASCADE CONSTRAINTS;
DROP TABLE VEHICLES CASCADE CONSTRAINTS;
DROP TABLE VEHICLE_CATEGORIES CASCADE CONSTRAINTS;
DROP TABLE MANUFACTURERS CASCADE CONSTRAINTS;
DROP TABLE BRANCHES CASCADE CONSTRAINTS;
DROP TABLE PARTS_VENDORS CASCADE CONSTRAINTS;
DROP TABLE POLICY_PROVIDER CASCADE CONSTRAINTS;
DROP TABLE INSURANCE_POLICIES CASCADE CONSTRAINTS;


-- tables 


CREATE TABLE POLICY_PROVIDER (
    provider_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_name VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL,
    Phone_number VARCHAR2(12) NOT NULL,
    Claims_phone VARCHAR2(12) NOT NULL,
    online_portal VARCHAR2(255)
);

CREATE TABLE INSURANCE_POLICIES (
    insurance_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    insurance_type VARCHAR2(255),
    price NUMBER,
    policy_status VARCHAR2(7) DEFAULT 'Pending' CHECK ( policy_status IN ('Active', 'Expired','Pending')) ,
    provider_ID NUMBER,
    FOREIGN KEY (provider_ID) REFERENCES POLICY_PROVIDER(provider_ID) 
);

CREATE TABLE BRANCHES (
   branch_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   branch_name VARCHAR2(100) NOT NULL,
   city VARCHAR2(50) NOT NULL,
   address VARCHAR2(200),
   phone VARCHAR2(20),
   created_date DATE DEFAULT SYSDATE
);

CREATE TABLE VEHICLE_CATEGORIES (
   category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   category_name VARCHAR2(50) NOT NULL UNIQUE,
   description VARCHAR2(200),
   created_date DATE DEFAULT SYSDATE
);

CREATE TABLE MANUFACTURERS (
   manufacturer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   manufacturer_name VARCHAR2(100) NOT NULL,
   Country VARCHAR2(50) NOT NULL, 
   contact_phone VARCHAR2(20),
   email varchar2(50),
   CONSTRAINT uq_manufacturer_contry UNIQUE (manufacturer_name, Country)
);

CREATE TABLE VEHICLES (
   vehicle_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   vin VARCHAR2(17) NOT NULL UNIQUE,
   model VARCHAR2(50) NOT NULL,
   year NUMBER(4) NOT NULL,
   category_id NUMBER NOT NULL,
   manufacturer_id NUMBER NOT NULL,
   daily_rate NUMBER(8,2) NOT NULL,
   branch_id NUMBER NOT NULL,
   status VARCHAR2(20) DEFAULT 'Available' CHECK (status IN ('Available', 'Unavailable', 'Maintenance', 'Out-of-Service')),
   purchase_date DATE,
   mileage NUMBER(7) DEFAULT 0,
   created_date DATE DEFAULT SYSDATE,
   insurance_ID NUMBER,
   FOREIGN KEY (insurance_ID) REFERENCES INSURANCE_POLICIES(insurance_ID),
   FOREIGN KEY (category_id) REFERENCES VEHICLE_CATEGORIES(category_id),
   FOREIGN KEY (manufacturer_id) REFERENCES MANUFACTURERS(manufacturer_id),
   FOREIGN KEY (branch_id) REFERENCES BRANCHES(branch_id),
   CHECK (year >= 2015 AND year <= 2026)
);

CREATE TABLE VEHICLE_MAINTENANCE (
   maintenance_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   vehicle_id NUMBER NOT NULL,
   maintenance_type VARCHAR2(100) NOT NULL,
   scheduled_date DATE NOT NULL,
   completion_date DATE,
   status VARCHAR2(20) DEFAULT 'Scheduled' CHECK (status IN ('Scheduled', 'In Progress', 'Completed', 'Cancelled')),
   cost NUMBER(8,2),
   notes VARCHAR2(500),
   created_date DATE DEFAULT SYSDATE,
   FOREIGN KEY (vehicle_id) REFERENCES VEHICLES(vehicle_id),
   CHECK (completion_date IS NULL OR completion_date >= scheduled_date)
);

CREATE TABLE RENTAL_CUSTOMERS (
   customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   first_name VARCHAR2(50) NOT NULL,
   last_name VARCHAR2(50) NOT NULL,
   email VARCHAR2(100) NOT NULL UNIQUE,
   phone VARCHAR2(20),
   address VARCHAR2(200),
   account_type VARCHAR2(20) DEFAULT 'Individual' CHECK (account_type IN ('Individual', 'Corporate')),
   membership_date DATE DEFAULT SYSDATE,
   total_rentals NUMBER DEFAULT 0,
   lifetime_spending NUMBER(10,2) DEFAULT 0,
   created_date DATE DEFAULT SYSDATE
);

CREATE TABLE DRIVER_LICENSES (
   license_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   customer_id NUMBER NOT NULL UNIQUE,
   license_number VARCHAR2(30) NOT NULL UNIQUE,
   license_Province VARCHAR2(20),
   expiry_date DATE NOT NULL,
   created_date DATE DEFAULT SYSDATE,
   verified VARCHAR2(1) DEFAULT 'N' CHECK (verified IN ('Y', 'N')),
   FOREIGN KEY (customer_id) REFERENCES RENTAL_CUSTOMERS(customer_id)
);

CREATE TABLE RESERVATIONS (
   reservation_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   customer_id NUMBER NOT NULL,
   vehicle_id NUMBER NOT NULL,
   pickup_branch_id NUMBER NOT NULL,
   dropoff_branch_id NUMBER NOT NULL,
   pickup_date DATE NOT NULL,
   dropoff_date DATE NOT NULL,
   status VARCHAR2(20) DEFAULT 'Pending' CHECK (status IN ('Pending', 'Confirmed', 'Cancelled', 'Completed')),
   reserved_date DATE DEFAULT SYSDATE,
   estimated_cost NUMBER(10,2),
   notes VARCHAR2(500),
   created_date DATE DEFAULT SYSDATE,
   FOREIGN KEY (customer_id) REFERENCES RENTAL_CUSTOMERS(customer_id),
   FOREIGN KEY (vehicle_id) REFERENCES VEHICLES(vehicle_id),
   FOREIGN KEY (pickup_branch_id) REFERENCES BRANCHES(branch_id),
   FOREIGN KEY (dropoff_branch_id) REFERENCES BRANCHES(branch_id),
   CHECK (dropoff_date > pickup_date)
);

CREATE TABLE RENTALS (
   rental_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   customer_id NUMBER NOT NULL,
   vehicle_id NUMBER NOT NULL,
   reservation_id NUMBER,
   pickup_branch_id NUMBER NOT NULL,
   dropoff_branch_id NUMBER NOT NULL,
   pickup_date DATE NOT NULL,
   dropoff_date DATE NOT NULL,
   actual_return_date DATE,
   daily_rate NUMBER(8,2) NOT NULL,
   total_cost NUMBER(10,2),
   status VARCHAR2(20) DEFAULT 'Active' CHECK (status IN ('Active', 'Completed', 'Cancelled')),
   created_date DATE DEFAULT SYSDATE,
   FOREIGN KEY (customer_id) REFERENCES RENTAL_CUSTOMERS(customer_id),
   FOREIGN KEY (vehicle_id) REFERENCES VEHICLES(vehicle_id),
   FOREIGN KEY (pickup_branch_id) REFERENCES BRANCHES(branch_id),
   FOREIGN KEY (dropoff_branch_id) REFERENCES BRANCHES(branch_id),
   CHECK (actual_return_date IS NULL OR actual_return_date >= pickup_date)
);

CREATE TABLE FAVORITES (
   favorite_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   customer_id NUMBER NOT NULL,
   vehicle_id NUMBER NOT NULL,
   added_date DATE DEFAULT SYSDATE,
   FOREIGN KEY (customer_id) REFERENCES RENTAL_CUSTOMERS(customer_id),
   FOREIGN KEY (vehicle_id) REFERENCES VEHICLES(vehicle_id),
   UNIQUE (customer_id, vehicle_id)
);

CREATE TABLE LOYALTY_TIERS (
   tier_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   tier_name VARCHAR2(50) NOT NULL UNIQUE,
   discount_percentage NUMBER(5,2),
   benefits VARCHAR2(500)
);

CREATE TABLE CUSTOMER_LOYALTY (
   loyalty_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   customer_id NUMBER NOT NULL UNIQUE,
   tier_id NUMBER NOT NULL,
   rental_count NUMBER DEFAULT 0,
   last_updated DATE DEFAULT SYSDATE,
   FOREIGN KEY (customer_id) REFERENCES RENTAL_CUSTOMERS(customer_id),
   FOREIGN KEY (tier_id) REFERENCES LOYALTY_TIERS(tier_id)
);

CREATE TABLE PARTS_VENDORS (
   vendor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   vendor_name VARCHAR2(100) NOT NULL UNIQUE,
   phone VARCHAR2(20),
   Country VARCHAR2(50) NOT NULL,
   address VARCHAR2(200),
   email VARCHAR2(100),
   created_date DATE DEFAULT SYSDATE
);

CREATE TABLE PROCUREMENT_RECORDS (
   procurement_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   vendor_id NUMBER NOT NULL,
   manufacturer_id NUMBER,
   vehicle_id NUMBER,
   part_name VARCHAR2(100) NOT NULL,
   part_number VARCHAR2(50) NOT NULL UNIQUE,
   quantity NUMBER NOT NULL,
   unit_cost NUMBER(8,2) NOT NULL,
   order_date DATE DEFAULT SYSDATE,
   delivery_date DATE,
   total_cost NUMBER(10,2),
   status VARCHAR2(20) DEFAULT 'Pending' CHECK (status IN ('Pending', 'Ordered', 'Delivered', 'Cancelled')),
   notes VARCHAR2(500),
   FOREIGN KEY (vendor_id) REFERENCES PARTS_VENDORS(vendor_id),
   FOREIGN KEY (manufacturer_id) REFERENCES MANUFACTURERS(manufacturer_id),
   FOREIGN KEY (vehicle_id) REFERENCES VEHICLES(vehicle_id),
   CONSTRAINT chk_delivery CHECK ( not ( status = 'Delivered' and delivery_date is null)),
   CONSTRAINT chk_delivery_date CHECK ( not ( status = 'Ordered' and delivery_date is null)),
   CONSTRAINT chk_Cancelled CHECK (not ( status = 'Cancelled' and delivery_date is not null))
);

CREATE TABLE DAMAGE_REPORT (
    damage_report_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rental_id NUMBER NOT NULL,
    vehicle_id NUMBER NOT NULL,
    damage_description VARCHAR2(1000),
    repair_cost NUMBER(10,2),
    report_date DATE DEFAULT SYSDATE,
    payment_status VARCHAR2(50),
    incident_status VARCHAR2(50) NOT NULL,
    CONSTRAINT fk_damage_rental FOREIGN KEY (rental_id) REFERENCES RENTALS(rental_id),
    CONSTRAINT fk_damage_vehicle FOREIGN KEY (vehicle_id) REFERENCES VEHICLES(vehicle_id)
);


-- Values 

 
INSERT INTO BRANCHES (branch_name,city,address,phone,created_date) VALUES ('Downtown Toronto', 'Toronto', '123 King St W', '416-555-0101', SYSDATE);
INSERT INTO BRANCHES (branch_name,city,address,phone,created_date) VALUES ('Pearson Airport', 'Toronto', '6301 Silver Dart Dr', '416-555-0102', SYSDATE);
INSERT INTO BRANCHES (branch_name,city,address,phone,created_date) VALUES ('Vancouver Main', 'Vancouver', '456 Granville St', '604-555-0103', SYSDATE);
INSERT INTO BRANCHES (branch_name,city,address,phone,created_date) VALUES ('Vancouver Airport', 'Vancouver', '3440 Cessna Dr', '604-555-0104', SYSDATE);
INSERT INTO BRANCHES (branch_name,city,address,phone,created_date) VALUES ('Montreal Downtown', 'Montreal', '789 Rue Sainte-Catherine', '514-555-0105', SYSDATE);
INSERT INTO BRANCHES (branch_name,city,address,phone,created_date) VALUES ('Montreal Trudeau', 'Montreal', '975 Blvd. Roméo-Vachon N', '514-555-0106', SYSDATE);
INSERT INTO BRANCHES (branch_name,city,address,phone,created_date) VALUES ('Calgary Hub', 'Calgary', '321 Centre St N', '403-555-0107', SYSDATE);
INSERT INTO BRANCHES (branch_name,city,address,phone,created_date) VALUES ('Calgary Airport', 'Calgary', '2000 Airport Rd NE', '403-555-0108', SYSDATE);
INSERT INTO BRANCHES (branch_name,city,address,phone,created_date) VALUES ('Edmonton Central', 'Edmonton', '654 Jasper Ave', '780-555-0109', SYSDATE);
INSERT INTO BRANCHES (branch_name,city,address,phone,created_date) VALUES ('Winnipeg Station', 'Winnipeg', '987 Portage Ave', '204-555-0110', SYSDATE);
COMMIT;

INSERT INTO POLICY_PROVIDER (provider_name, email, Phone_number, Claims_phone, online_portal) VALUES ('Intact Financial Corporation', 'fleet@intact.ca', '18002681311', '18664642424', 'https://www.intact.ca');
INSERT INTO POLICY_PROVIDER (provider_name, email, Phone_number, Claims_phone, online_portal) VALUES ('Aviva Canada', 'commercial.fleet@aviva.com', '18003874518', '18666928482', 'https://www.aviva.ca');
INSERT INTO POLICY_PROVIDER (provider_name, email, Phone_number, Claims_phone, online_portal) VALUES ('Desjardins Insurance', 'commercial@desjardins.com', '18004635600', '18003618080', 'https://www.desjardinsinsurance.com');
INSERT INTO POLICY_PROVIDER (provider_name, email, Phone_number, Claims_phone, online_portal) VALUES ('Northbridge Insurance', 'fleetclaims@northbridge.ca', '18002689680', '18556212497', 'https://www.northbridgeinsurance.ca');
INSERT INTO POLICY_PROVIDER (provider_name, email, Phone_number, Claims_phone, online_portal) VALUES ('The Co-operators', 'commercial_service@cooperators.ca', '18775452667', '18888182242', 'https://www.cooperators.ca');

INSERT INTO INSURANCE_POLICIES (insurance_type, price, policy_status, provider_ID) VALUES ('Commercial Auto Liability ($2M)', 1450.00, 'Active', 1);
INSERT INTO INSURANCE_POLICIES (insurance_type, price, policy_status, provider_ID) VALUES ('Commercial Auto Liability ($2M)', 1450.00, 'Active', 1);
INSERT INTO INSURANCE_POLICIES (insurance_type, price, policy_status, provider_ID) VALUES ('Fleet Collision Comprehensive', 1650.00, 'Active', 2);
INSERT INTO INSURANCE_POLICIES (insurance_type, price, policy_status, provider_ID) VALUES ('Fleet Collision Comprehensive', 1650.00, 'Active', 2);
INSERT INTO INSURANCE_POLICIES (insurance_type, price, policy_status, provider_ID) VALUES ('Commercial Excess Liability ($5M)', 2200.00, 'Active', 3);
INSERT INTO INSURANCE_POLICIES (insurance_type, price, policy_status, provider_ID) VALUES ('Commercial Excess Liability ($5M)', 2400.00, 'Active', 3);
INSERT INTO INSURANCE_POLICIES (insurance_type, price, policy_status, provider_ID) VALUES ('EV Fleet Comprehensive Tech', 1850.00, 'Active', 4);
INSERT INTO INSURANCE_POLICIES (insurance_type, price, policy_status, provider_ID) VALUES ('Commercial Auto Liability ($1M)', 1350.00, 'Pending', 5);
INSERT INTO INSURANCE_POLICIES (insurance_type, price, policy_status, provider_ID) VALUES ('Fleet Collision Coverage', 1500.00, 'Active', 1);
INSERT INTO INSURANCE_POLICIES (insurance_type, price, policy_status, provider_ID) VALUES ('Fleet Comprehensive Coverage', 1550.00, 'Active', 2);
INSERT INTO INSURANCE_POLICIES (insurance_type, price, policy_status, provider_ID) VALUES ('Commercial Auto Liability ($2M)', 1700.00, 'Active', 3);
INSERT INTO INSURANCE_POLICIES (insurance_type, price, policy_status, provider_ID) VALUES ('Passenger Van Fleet Protection', 1600.00, 'Active', 4);
INSERT INTO INSURANCE_POLICIES (insurance_type, price, policy_status, provider_ID) VALUES ('Commercial Truck Haulage Liability', 1950.00, 'Active', 5);
INSERT INTO INSURANCE_POLICIES (insurance_type, price, policy_status, provider_ID) VALUES ('Commercial Fleet Standard', 1400.00, 'Active', 1);
INSERT INTO INSURANCE_POLICIES (insurance_type, price, policy_status, provider_ID) VALUES ('Commercial Fleet Standard', 1400.00, 'Active', 2);

INSERT INTO VEHICLE_CATEGORIES(category_name,description,created_date) VALUES ('Economy', 'Budget-friendly compact cars',SYSDATE);
INSERT INTO VEHICLE_CATEGORIES(category_name,description,created_date) VALUES ('Sedan', 'Mid-size comfortable sedans',SYSDATE);
INSERT INTO VEHICLE_CATEGORIES(category_name,description,created_date) VALUES ('SUV', 'Sport utility vehicles',SYSDATE);
INSERT INTO VEHICLE_CATEGORIES(category_name,description,created_date) VALUES ('Luxury', 'Premium luxury vehicles',SYSDATE);
INSERT INTO VEHICLE_CATEGORIES(category_name,description,created_date) VALUES ('Electric', 'Electric and hybrid vehicles',SYSDATE);
INSERT INTO VEHICLE_CATEGORIES(category_name,description,created_date) VALUES ('Truck', 'Pickup trucks and vans',SYSDATE);
INSERT INTO VEHICLE_CATEGORIES(category_name,description,created_date) VALUES ('Sports', 'High-performance sports cars',SYSDATE);
COMMIT;

INSERT INTO MANUFACTURERS(manufacturer_name,Country,contact_phone,email) VALUES ('Toyota', 'Canada','1 416-438-6320', 'philippe_crowe@toyota.ca');
INSERT INTO MANUFACTURERS(manufacturer_name,Country,contact_phone,email) VALUES ('Honda', 'Canada', '1 905-888-8110', 'N/A');
INSERT INTO MANUFACTURERS(manufacturer_name,Country,contact_phone,email) VALUES ('Ford', 'Canada',  '1 905-845-2511', 'N/A');
INSERT INTO MANUFACTURERS(manufacturer_name,Country,contact_phone,email) VALUES ('Chevrolet', 'Canada', '1 905-644-5000', 'N/A');
INSERT INTO MANUFACTURERS(manufacturer_name,Country,contact_phone,email) VALUES ('BMW', 'Canada', '1 905-858-0500', 'corpratefleet@bmw.ca');
INSERT INTO MANUFACTURERS(manufacturer_name,Country,contact_phone,email) VALUES ('Mercedes-Benz', 'Canada', '1 416-847-7500', 'N/A');
INSERT INTO MANUFACTURERS(manufacturer_name,Country,contact_phone,email) VALUES ('Tesla', 'USA', '1 648-260-0112', 'fleet@tesla.com');
INSERT INTO MANUFACTURERS(manufacturer_name,Country,contact_phone,email) VALUES ('Hyundai', 'Canada', '1 905-477-0202', 'pr@hyundaicanada.com');
COMMIT; -- yes i did spend a few hours getting the real contact infomation if you dislike it just know this is real infomation that is public
 
INSERT INTO VEHICLES(vin,model,year,category_id,manufacturer_id,daily_rate,branch_id,status,purchase_date,mileage,created_date) VALUES ('WBADT43452G915187', 'Corolla', 2024, 1, 1, 49.99, 1, 'Available', TO_DATE('2023-06-15','YYYY-MM-DD'), 5200, SYSDATE);
INSERT INTO VEHICLES(vin,model,year,category_id,manufacturer_id,daily_rate,branch_id,status,purchase_date,mileage,created_date) VALUES ('JTDKN3AU4D5031849', 'Civic', 2023, 1, 2, 54.99, 1, 'Available', TO_DATE('2022-08-20','YYYY-MM-DD'), 18450, SYSDATE);
INSERT INTO VEHICLES(vin,model,year,category_id,manufacturer_id,daily_rate,branch_id,status,purchase_date,mileage,created_date) VALUES ('1FADP5AU19L478932', 'Focus', 2024, 1, 3, 55.99, 2, 'Available', TO_DATE('2023-11-10','YYYY-MM-DD'), 3200, SYSDATE);
INSERT INTO VEHICLES(vin,model,year,category_id,manufacturer_id,daily_rate,branch_id,status,purchase_date,mileage,created_date) VALUES ('1G1PB5S96F1103895', 'Cruze', 2024, 2, 4, 65.99, 1, 'Unavailable', TO_DATE('2023-09-05','YYYY-MM-DD'), 12100, SYSDATE);
INSERT INTO VEHICLES(vin,model,year,category_id,manufacturer_id,daily_rate,branch_id,status,purchase_date,mileage,created_date) VALUES ('WBADT43482G876543', '320i', 2024, 4, 5, 125.99, 2, 'Available', TO_DATE('2023-07-30','YYYY-MM-DD'), 4800, SYSDATE);
INSERT INTO VEHICLES(vin,model,year,category_id,manufacturer_id,daily_rate,branch_id,status,purchase_date,mileage,created_date) VALUES ('WDBEF7DB0GA123456', 'C-Class', 2023, 4, 6, 145.99, 3, 'Available', TO_DATE('2022-05-12','YYYY-MM-DD'), 28650, SYSDATE);
INSERT INTO VEHICLES(vin,model,year,category_id,manufacturer_id,daily_rate,branch_id,status,purchase_date,mileage,created_date) VALUES ('5TDJKRFH6LS123456', 'Model 3', 2024, 5, 7, 99.99, 1, 'Available', TO_DATE('2023-03-20','YYYY-MM-DD'), 8900, SYSDATE);
INSERT INTO VEHICLES(vin,model,year,category_id,manufacturer_id,daily_rate,branch_id,status,purchase_date,mileage,created_date) VALUES ('KMHEC4A4XJU123456', 'Elantra', 2024, 1, 8, 52.99, 3, 'Maintenance', TO_DATE('2023-10-15','YYYY-MM-DD'), 6200, SYSDATE);
INSERT INTO VEHICLES(vin,model,year,category_id,manufacturer_id,daily_rate,branch_id,status,purchase_date,mileage,created_date) VALUES ('2T1BURFE0JC123456', 'RAV4', 2024, 3, 1, 79.99, 2, 'Available', TO_DATE('2023-04-08','YYYY-MM-DD'), 11300, SYSDATE);
INSERT INTO VEHICLES(vin,model,year,category_id,manufacturer_id,daily_rate,branch_id,status,purchase_date,mileage,created_date) VALUES ('5TEEU6H59LZ123456', 'CR-V', 2023, 3, 2, 84.99, 1, 'Available', TO_DATE('2022-12-20','YYYY-MM-DD'), 22400, SYSDATE);
INSERT INTO VEHICLES(vin,model,year,category_id,manufacturer_id,daily_rate,branch_id,status,purchase_date,mileage,created_date) VALUES ('1FTEX1A81EFA12345', 'Explorer', 2024, 3, 3, 89.99, 4, 'Unavailable', TO_DATE('2023-08-10','YYYY-MM-DD'), 9100, SYSDATE);
INSERT INTO VEHICLES(vin,model,year,category_id,manufacturer_id,daily_rate,branch_id,status,purchase_date,mileage,created_date) VALUES ('JHLRE6H57LC123456', 'Odyssey', 2023, 6, 2, 95.99, 5, 'Available', TO_DATE('2022-11-05','YYYY-MM-DD'), 19800, SYSDATE);
INSERT INTO VEHICLES(vin,model,year,category_id,manufacturer_id,daily_rate,branch_id,status,purchase_date,mileage,created_date) VALUES ('1C6RR5FT4JS123456', 'Silverado', 2024, 6, 4, 105.99, 3, 'Available', TO_DATE('2023-07-22','YYYY-MM-DD'), 14500, SYSDATE);
INSERT INTO VEHICLES(vin,model,year,category_id,manufacturer_id,daily_rate,branch_id,status,purchase_date,mileage,created_date) VALUES ('JT2BF18K8M0123456', 'Camry', 2024, 2, 1, 69.99, 2, 'Available', TO_DATE('2023-05-18','YYYY-MM-DD'), 8750, SYSDATE);
INSERT INTO VEHICLES(vin,model,year,category_id,manufacturer_id,daily_rate,branch_id,status,purchase_date,mileage,created_date) VALUES ('2HGCV52635H123456', 'Accord', 2024, 2, 2, 74.99, 4, 'Available', TO_DATE('2023-06-25','YYYY-MM-DD'), 7200, SYSDATE);
COMMIT;

INSERT INTO VEHICLE_MAINTENANCE(vehicle_id,maintenance_type,scheduled_date,completion_date,status,cost,notes,created_date) VALUES (1, 'Oil Change', TO_DATE('2026-02-15','YYYY-MM-DD'), NULL, 'Scheduled', 89.99, 'Regular maintenance', SYSDATE);
INSERT INTO VEHICLE_MAINTENANCE(vehicle_id,maintenance_type,scheduled_date,completion_date,status,cost,notes,created_date) VALUES (2, 'Tire Rotation', TO_DATE('2026-02-20','YYYY-MM-DD'), TO_DATE('2026-02-20','YYYY-MM-DD'), 'Completed', 59.99, 'Preventive maintenance', SYSDATE);
INSERT INTO VEHICLE_MAINTENANCE(vehicle_id,maintenance_type,scheduled_date,completion_date,status,cost,notes,created_date) VALUES (8, 'Engine Inspection', TO_DATE('2026-01-25','YYYY-MM-DD'), TO_DATE('2026-01-26','YYYY-MM-DD'), 'Completed', 150.00, 'Diagnostic check', SYSDATE);
INSERT INTO VEHICLE_MAINTENANCE(vehicle_id,maintenance_type,scheduled_date,completion_date,status,cost,notes,created_date) VALUES (4, 'Brake Service', TO_DATE('2026-03-10','YYYY-MM-DD'), NULL, 'In Progress', 299.99, 'Brake pad replacement', SYSDATE);
INSERT INTO VEHICLE_MAINTENANCE(vehicle_id,maintenance_type,scheduled_date,completion_date,status,cost,notes,created_date) VALUES (5, 'Battery Test', TO_DATE('2026-02-28','YYYY-MM-DD'), NULL, 'Scheduled', 125.00, 'Winter check', SYSDATE);
INSERT INTO VEHICLE_MAINTENANCE(vehicle_id,maintenance_type,scheduled_date,completion_date,status,cost,notes,created_date) VALUES (9, 'Transmission Fluid', TO_DATE('2026-03-05','YYYY-MM-DD'), NULL, 'Scheduled', 189.99, 'Fluid replacement', SYSDATE);
INSERT INTO VEHICLE_MAINTENANCE(vehicle_id,maintenance_type,scheduled_date,completion_date,status,cost,notes,created_date) VALUES (1, 'Air Filter Change', TO_DATE('2026-02-10','YYYY-MM-DD'), TO_DATE('2026-02-11','YYYY-MM-DD'), 'Completed', 45.00, 'Regular maintenance', SYSDATE);
INSERT INTO VEHICLE_MAINTENANCE(vehicle_id,maintenance_type,scheduled_date,completion_date,status,cost,notes,created_date) VALUES (4, 'Coolant Flush', TO_DATE('2026-02-25','YYYY-MM-DD'), NULL, 'Scheduled', 125.00, 'System maintenance', SYSDATE);
INSERT INTO VEHICLE_MAINTENANCE(vehicle_id,maintenance_type,scheduled_date,completion_date,status,cost,notes,created_date) VALUES (7, 'Software Update', TO_DATE('2026-02-15','YYYY-MM-DD'), TO_DATE('2026-02-15','YYYY-MM-DD'), 'Completed', 199.99, 'Tesla update', SYSDATE);
INSERT INTO VEHICLE_MAINTENANCE(vehicle_id,maintenance_type,scheduled_date,completion_date,status,cost,notes,created_date) VALUES (5, 'Alignment Check', TO_DATE('2026-03-20','YYYY-MM-DD'), NULL, 'Scheduled', 99.99, 'Wheel alignment', SYSDATE);
COMMIT;

INSERT INTO RENTAL_CUSTOMERS(first_name,last_name,email,phone,address,account_type,membership_date,total_rentals,lifetime_spending,created_date) VALUES ('Jeffin', 'Francis', 'jeffin.f@email.com', '416-555-2001', '100 King St, Toronto', 'Individual', SYSDATE-730, 8, 4500.00, SYSDATE);
INSERT INTO RENTAL_CUSTOMERS(first_name,last_name,email,phone,address,account_type,membership_date,total_rentals,lifetime_spending,created_date) VALUES ('Becca', 'Pennington', 'becca.p@email.com', '416-555-2002', '200 Queen St, Toronto', 'Individual', SYSDATE-365, 3, 1200.00, SYSDATE);
INSERT INTO RENTAL_CUSTOMERS(first_name,last_name,email,phone,address,account_type,membership_date,total_rentals,lifetime_spending,created_date) VALUES ('Tristin', 'Forbes', 'tristin.f@email.com', '604-555-2003', '300 Granville St, Vancouver', 'Individual', SYSDATE-180, 2, 600.00, SYSDATE);
INSERT INTO RENTAL_CUSTOMERS(first_name,last_name,email,phone,address,account_type,membership_date,total_rentals,lifetime_spending,created_date) VALUES ('Sunesh', 'Shrestha', 'sunesh.s@email.com', '514-555-2004', '400 St Catherine, Montreal', 'Individual', SYSDATE-90, 1, 150.00, SYSDATE);
INSERT INTO RENTAL_CUSTOMERS(first_name,last_name,email,phone,address,account_type,membership_date,total_rentals,lifetime_spending,created_date) VALUES ('Jennifer', 'Brown', 'jen.brown@email.com', '403-555-2005', '500 Centre St, Calgary', 'Individual', SYSDATE-730, 12, 6800.00, SYSDATE);
INSERT INTO RENTAL_CUSTOMERS(first_name,last_name,email,phone,address,account_type,membership_date,total_rentals,lifetime_spending,created_date) VALUES ('Lisa', 'Garcia', 'lisa.garcia@email.com', '780-555-2006', '600 Jasper Ave, Edmonton', 'Corporate', SYSDATE-365, 15, 8900.00, SYSDATE);
INSERT INTO RENTAL_CUSTOMERS(first_name,last_name,email,phone,address,account_type,membership_date,total_rentals,lifetime_spending,created_date) VALUES ('David', 'Martinez', 'david.m@email.com', '204-555-2007', '700 Portage Ave, Winnipeg', 'Individual', SYSDATE-540, 5, 2400.00, SYSDATE);
INSERT INTO RENTAL_CUSTOMERS(first_name,last_name,email,phone,address,account_type,membership_date,total_rentals,lifetime_spending,created_date) VALUES ('Emma', 'Taylor', 'emma.taylor@email.com', '416-555-2008', '800 Front St, Toronto', 'Individual', SYSDATE-30, 1, 175.00, SYSDATE);
INSERT INTO RENTAL_CUSTOMERS(first_name,last_name,email,phone,address,account_type,membership_date,total_rentals,lifetime_spending,created_date) VALUES ('Christopher', 'Anderson', 'c.anderson@email.com', '604-555-2009', '900 Burrard St, Vancouver', 'Individual', SYSDATE-270, 4, 1900.00, SYSDATE);
INSERT INTO RENTAL_CUSTOMERS(first_name,last_name,email,phone,address,account_type,membership_date,total_rentals,lifetime_spending,created_date) VALUES ('Amanda', 'Thomas', 'amanda.t@email.com', '514-555-2010', '1000 Blvd de Maisonneuve, Montreal', 'Corporate', SYSDATE-120, 6, 3500.00, SYSDATE);
COMMIT;

INSERT INTO DRIVER_LICENSES(customer_id,license_number,license_Province,expiry_date,created_date,verified) VALUES(1, 'DL12345678', 'ON', TO_DATE('2026-06-15','YYYY-MM-DD'), SYSDATE,'N');
INSERT INTO DRIVER_LICENSES(customer_id,license_number,license_Province,expiry_date,created_date,verified) VALUES (2, 'DL23456789', 'ON', TO_DATE('2027-09-20','YYYY-MM-DD'), SYSDATE,'N');
INSERT INTO DRIVER_LICENSES(customer_id,license_number,license_Province,expiry_date,created_date,verified) VALUES (3, 'DL34567890', 'BC', TO_DATE('2026-12-15','YYYY-MM-DD'), SYSDATE,'N');
INSERT INTO DRIVER_LICENSES(customer_id,license_number,license_Province,expiry_date,created_date,verified) VALUES (4, 'DL45678901', 'QC', TO_DATE('2025-08-10','YYYY-MM-DD'), SYSDATE,'Y');
INSERT INTO DRIVER_LICENSES(customer_id,license_number,license_Province,expiry_date,created_date,verified) VALUES (5, 'DL56789012', 'AB', TO_DATE('2027-03-25','YYYY-MM-DD'), SYSDATE,'Y');
INSERT INTO DRIVER_LICENSES(customer_id,license_number,license_Province,expiry_date,created_date,verified) VALUES (6, 'DL67890123', 'AB', TO_DATE('2026-11-12','YYYY-MM-DD'), SYSDATE,'N');
INSERT INTO DRIVER_LICENSES(customer_id,license_number,license_Province,expiry_date,created_date,verified) VALUES (7, 'DL78901234', 'MB', TO_DATE('2027-05-18','YYYY-MM-DD'), SYSDATE,'Y');
INSERT INTO DRIVER_LICENSES(customer_id,license_number,license_Province,expiry_date,created_date,verified) VALUES (8, 'DL89012345', 'ON', TO_DATE('2028-01-22','YYYY-MM-DD'), SYSDATE,'Y');
INSERT INTO DRIVER_LICENSES(customer_id,license_number,license_Province,expiry_date,created_date,verified) VALUES (9, 'DL90123456', 'BC', TO_DATE('2026-07-08','YYYY-MM-DD'),  SYSDATE,'Y');
INSERT INTO DRIVER_LICENSES(customer_id,license_number,license_Province,expiry_date,created_date,verified) VALUES (10, 'DL01234567', 'QC', TO_DATE('2027-02-14','YYYY-MM-DD'), SYSDATE,'Y');
COMMIT;

INSERT INTO LOYALTY_TIERS(tier_name,discount_percentage,benefits) VALUES ('Regular', 0, 'Standard rental terms');
INSERT INTO LOYALTY_TIERS(tier_name,discount_percentage,benefits) VALUES ('Gold', 5, '5% discount, priority support');
INSERT INTO LOYALTY_TIERS(tier_name,discount_percentage,benefits) VALUES ('VIP', 10, '10% discount, free upgrades, concierge');
COMMIT;

INSERT INTO CUSTOMER_LOYALTY(customer_id,tier_id,rental_count,last_updated) VALUES (1, 3,  8, SYSDATE);
INSERT INTO CUSTOMER_LOYALTY(customer_id,tier_id,rental_count,last_updated) VALUES (2, 2, 3, SYSDATE);
INSERT INTO CUSTOMER_LOYALTY(customer_id,tier_id,rental_count,last_updated) VALUES (3, 1, 2, SYSDATE);
INSERT INTO CUSTOMER_LOYALTY(customer_id,tier_id,rental_count,last_updated) VALUES (4, 1, 1, SYSDATE);
INSERT INTO CUSTOMER_LOYALTY(customer_id,tier_id,rental_count,last_updated) VALUES (5, 3, 12, SYSDATE);
INSERT INTO CUSTOMER_LOYALTY(customer_id,tier_id,rental_count,last_updated) VALUES (6, 3, 15, SYSDATE);
INSERT INTO CUSTOMER_LOYALTY(customer_id,tier_id,rental_count,last_updated) VALUES (7, 2,5, SYSDATE);
INSERT INTO CUSTOMER_LOYALTY(customer_id,tier_id,rental_count,last_updated) VALUES (8, 1, 1, SYSDATE);
INSERT INTO CUSTOMER_LOYALTY(customer_id,tier_id,rental_count,last_updated) VALUES (9, 2,  4, SYSDATE);
INSERT INTO CUSTOMER_LOYALTY(customer_id,tier_id,rental_count,last_updated) VALUES (10, 3,  6, SYSDATE);
COMMIT;

INSERT INTO RESERVATIONS(customer_id,vehicle_id,pickup_branch_id,dropoff_branch_id,pickup_date,dropoff_date,status,reserved_date,estimated_cost,notes,created_date) VALUES (1, 4, 1, 3, TO_DATE('2026-03-01','YYYY-MM-DD'), TO_DATE('2026-03-05','YYYY-MM-DD'), 'Confirmed', SYSDATE, 263.96, 'Business trip', SYSDATE);
INSERT INTO RESERVATIONS(customer_id,vehicle_id,pickup_branch_id,dropoff_branch_id,pickup_date,dropoff_date,status,reserved_date,estimated_cost,notes,created_date) VALUES (2, 9, 1, 2, TO_DATE('2026-03-10','YYYY-MM-DD'), TO_DATE('2026-03-12','YYYY-MM-DD'), 'Confirmed', SYSDATE, 159.98, 'Weekend getaway', SYSDATE);
INSERT INTO RESERVATIONS(customer_id,vehicle_id,pickup_branch_id,dropoff_branch_id,pickup_date,dropoff_date,status,reserved_date,estimated_cost,notes,created_date) VALUES (3, 5, 3, 1, TO_DATE('2026-03-15','YYYY-MM-DD'), TO_DATE('2026-03-18','YYYY-MM-DD'), 'Pending', SYSDATE, 377.97, 'Family vacation', SYSDATE);
INSERT INTO RESERVATIONS(customer_id,vehicle_id,pickup_branch_id,dropoff_branch_id,pickup_date,dropoff_date,status,reserved_date,estimated_cost,notes,created_date) VALUES (5, 11, 4, 3, TO_DATE('2026-03-20','YYYY-MM-DD'), TO_DATE('2026-03-22','YYYY-MM-DD'), 'Confirmed', SYSDATE, 179.98, 'Client meeting', SYSDATE);
INSERT INTO RESERVATIONS(customer_id,vehicle_id,pickup_branch_id,dropoff_branch_id,pickup_date,dropoff_date,status,reserved_date,estimated_cost,notes,created_date) VALUES (6, 14, 5, 1, TO_DATE('2026-04-01','YYYY-MM-DD'), TO_DATE('2026-04-05','YYYY-MM-DD'), 'Confirmed', SYSDATE, 279.96, 'Corporate retreat', SYSDATE);
INSERT INTO RESERVATIONS(customer_id,vehicle_id,pickup_branch_id,dropoff_branch_id,pickup_date,dropoff_date,status,reserved_date,estimated_cost,notes,created_date) VALUES (9, 10, 3, 4, TO_DATE('2026-03-25','YYYY-MM-DD'), TO_DATE('2026-03-27','YYYY-MM-DD'), 'Pending', SYSDATE, 169.98, 'Business travel', SYSDATE);
INSERT INTO RESERVATIONS(customer_id,vehicle_id,pickup_branch_id,dropoff_branch_id,pickup_date,dropoff_date,status,reserved_date,estimated_cost,notes,created_date) VALUES (4, 6, 4, 2, TO_DATE('2026-03-30','YYYY-MM-DD'), TO_DATE('2026-04-02','YYYY-MM-DD'), 'Confirmed', SYSDATE, 583.96, 'Luxury trip', SYSDATE);
INSERT INTO RESERVATIONS(customer_id,vehicle_id,pickup_branch_id,dropoff_branch_id,pickup_date,dropoff_date,status,reserved_date,estimated_cost,notes,created_date) VALUES (7, 13, 3, 5, TO_DATE('2026-04-10','YYYY-MM-DD'), TO_DATE('2026-04-12','YYYY-MM-DD'), 'Confirmed', SYSDATE, 211.98, 'Adventure', SYSDATE);
INSERT INTO RESERVATIONS(customer_id,vehicle_id,pickup_branch_id,dropoff_branch_id,pickup_date,dropoff_date,status,reserved_date,estimated_cost,notes,created_date) VALUES (8, 7, 1, 3, TO_DATE('2026-04-15','YYYY-MM-DD'), TO_DATE('2026-04-18','YYYY-MM-DD'), 'Pending', SYSDATE, 299.97, 'Electric test drive', SYSDATE);
INSERT INTO RESERVATIONS(customer_id,vehicle_id,pickup_branch_id,dropoff_branch_id,pickup_date,dropoff_date,status,reserved_date,estimated_cost,notes,created_date) VALUES (10, 2, 4, 1, TO_DATE('2026-03-05','YYYY-MM-DD'), TO_DATE('2026-03-08','YYYY-MM-DD'), 'Confirmed', SYSDATE, 164.97, 'City visit', SYSDATE);
COMMIT;

INSERT INTO RENTALS(customer_id,vehicle_id,reservation_id,pickup_branch_id,dropoff_branch_id,pickup_date,dropoff_date,actual_return_date,daily_rate,total_cost,status,created_date) VALUES (1, 4, 1, 1, 3, TO_DATE('2026-02-01','YYYY-MM-DD'), TO_DATE('2026-02-05','YYYY-MM-DD'), TO_DATE('2026-02-05','YYYY-MM-DD'), 65.99, 329.95, 'Completed', SYSDATE);
INSERT INTO RENTALS(customer_id,vehicle_id,reservation_id,pickup_branch_id,dropoff_branch_id,pickup_date,dropoff_date,actual_return_date,daily_rate,total_cost,status,created_date) VALUES (2, 9, 2, 1, 2, TO_DATE('2026-02-08','YYYY-MM-DD'), TO_DATE('2026-02-10','YYYY-MM-DD'), TO_DATE('2026-02-10','YYYY-MM-DD'), 79.99, 479.94, 'Completed', SYSDATE);
INSERT INTO RENTALS(customer_id,vehicle_id,reservation_id,pickup_branch_id,dropoff_branch_id,pickup_date,dropoff_date,actual_return_date,daily_rate,total_cost,status,created_date) VALUES (5, 11, 4, 4, 3, TO_DATE('2026-02-15','YYYY-MM-DD'), TO_DATE('2026-02-17','YYYY-MM-DD'), TO_DATE('2026-02-17','YYYY-MM-DD'), 89.99, 449.95, 'Completed', SYSDATE);
INSERT INTO RENTALS(customer_id,vehicle_id,reservation_id,pickup_branch_id,dropoff_branch_id,pickup_date,dropoff_date,actual_return_date,daily_rate,total_cost,status,created_date) VALUES (1, 1, NULL, 1, 1, TO_DATE('2026-02-20','YYYY-MM-DD'), TO_DATE('2026-02-24','YYYY-MM-DD'), NULL, 49.99, NULL, 'Active', SYSDATE);
INSERT INTO RENTALS(customer_id,vehicle_id,reservation_id,pickup_branch_id,dropoff_branch_id,pickup_date,dropoff_date,actual_return_date,daily_rate,total_cost,status,created_date) VALUES (6, 14, 5, 5, 1, TO_DATE('2026-02-22','YYYY-MM-DD'), TO_DATE('2026-02-26','YYYY-MM-DD'), TO_DATE('2026-02-26','YYYY-MM-DD'), 69.99, 559.92, 'Completed', SYSDATE);
INSERT INTO RENTALS(customer_id,vehicle_id,reservation_id,pickup_branch_id,dropoff_branch_id,pickup_date,dropoff_date,actual_return_date,daily_rate,total_cost,status,created_date) VALUES (3, 6, 7, 4, 2, TO_DATE('2026-02-25','YYYY-MM-DD'), TO_DATE('2026-03-01','YYYY-MM-DD'), NULL, 145.99, NULL, 'Active', SYSDATE);
INSERT INTO RENTALS(customer_id,vehicle_id,reservation_id,pickup_branch_id,dropoff_branch_id,pickup_date,dropoff_date,actual_return_date,daily_rate,total_cost,status,created_date) VALUES (5, 10, NULL, 1, 2, TO_DATE('2026-03-01','YYYY-MM-DD'), TO_DATE('2026-03-03','YYYY-MM-DD'), NULL, 84.99, NULL, 'Active', SYSDATE);
INSERT INTO RENTALS(customer_id,vehicle_id,reservation_id,pickup_branch_id,dropoff_branch_id,pickup_date,dropoff_date,actual_return_date,daily_rate,total_cost,status,created_date) VALUES (7, 2, NULL, 2, 4, TO_DATE('2026-02-28','YYYY-MM-DD'), TO_DATE('2026-03-02','YYYY-MM-DD'), TO_DATE('2026-03-02','YYYY-MM-DD'), 54.99, 274.95, 'Completed', SYSDATE);
INSERT INTO RENTALS(customer_id,vehicle_id,reservation_id,pickup_branch_id,dropoff_branch_id,pickup_date,dropoff_date,actual_return_date,daily_rate,total_cost,status,created_date) VALUES (10, 13, 8, 3, 5, TO_DATE('2026-03-02','YYYY-MM-DD'), TO_DATE('2026-03-05','YYYY-MM-DD'), NULL, 105.99, NULL, 'Active', SYSDATE);
INSERT INTO RENTALS(customer_id,vehicle_id,reservation_id,pickup_branch_id,dropoff_branch_id,pickup_date,dropoff_date,actual_return_date,daily_rate,total_cost,status,created_date) VALUES (9, 7, 9, 1, 3, TO_DATE('2026-02-26','YYYY-MM-DD'), TO_DATE('2026-03-01','YYYY-MM-DD'), NULL, 99.99, NULL, 'Active', SYSDATE);
COMMIT;

INSERT INTO FAVORITES(customer_id,vehicle_id,added_date) VALUES (1, 6, SYSDATE-30);
INSERT INTO FAVORITES(customer_id,vehicle_id,added_date) VALUES (2, 5, SYSDATE-60);
INSERT INTO FAVORITES(customer_id,vehicle_id,added_date) VALUES (3, 7, SYSDATE-20);
INSERT INTO FAVORITES(customer_id,vehicle_id,added_date) VALUES (5, 12, SYSDATE-45);
INSERT INTO FAVORITES(customer_id,vehicle_id,added_date) VALUES (6, 6, SYSDATE-15);
INSERT INTO FAVORITES(customer_id,vehicle_id,added_date) VALUES (9, 11, SYSDATE-50);
INSERT INTO FAVORITES(customer_id,vehicle_id,added_date) VALUES (8, 5, SYSDATE-10);
INSERT INTO FAVORITES(customer_id,vehicle_id,added_date) VALUES (10, 3, SYSDATE-35);
INSERT INTO FAVORITES(customer_id,vehicle_id,added_date) VALUES (4, 7, SYSDATE-25);
INSERT INTO FAVORITES(customer_id,vehicle_id,added_date) VALUES (7, 9, SYSDATE-55);
COMMIT;

INSERT INTO PARTS_VENDORS(vendor_name,Country,phone,address,email) VALUES ('Lordco Auto Parts','Canada' , '1 604-467-1581', '1525 Kingsway Ave', 'info@lordco.com');
INSERT INTO PARTS_VENDORS(vendor_name,Country,phone,address,email) VALUES ('APC Auto Parts Centers','Canada' ,'1 519-268-7070', '2290 Scanian St', 'hr@canusa-apc.com');
INSERT INTO PARTS_VENDORS(vendor_name,Country,phone,address,email) VALUES ('Vast-Auto Distribution','Canada' , '1 515-955-3181', '4840 Boul. des Grandes-Pariries', 'info@vastauto.com');
INSERT INTO PARTS_VENDORS(vendor_name,Country,phone,address,email) VALUES ('Automotive Parts Ditrbutors', 'Canada' ,'1 403-253-2030', '138-5726 Burleigh Crescent SE', 'accounting@apdweblink.com');
INSERT INTO PARTS_VENDORS(vendor_name,Country,phone,address,email) VALUES ('Uni-Select Canada','Canada' , '1 800-641-2440', '170 Industriel Blvd', 'communications@uniselect.com');
INSERT INTO PARTS_VENDORS(vendor_name,Country,phone,address,email) VALUES ('PartsAvatar','Canada' , '1 844-850-5333','13540-102 Avenue Ste 1500', 'sales@partavatar.ca');
INSERT INTO PARTS_VENDORS(vendor_name,Country,phone,address,email) VALUES ('West Can Auto Parts','Canada' , '1 604-594-8800','12743 80 Ave', 'info@westcanauto.com');
INSERT INTO PARTS_VENDORS(vendor_name,Country,phone,address,email) VALUES ('Partsource','Canada' , '1 866-807-1902', '336 Corutland Ave', 'customerservice@canadiantire.ca');
INSERT INTO PARTS_VENDORS(vendor_name,Country,phone,address,email) VALUES ('NAPA Auto Parts','Canada' , '1 866-438-6272','7025 Rue Ontario E', 'info@napacanada.com');
INSERT INTO PARTS_VENDORS(vendor_name,Country,phone,address,email) VALUES ('Canada-Wide Parts Distrubtors','Canada','1 905-564-3116', 'Bay #3 7337 Pacifif Circel', 'f.t.sasota@canadawideaprts.com');
COMMIT; 

INSERT INTO DAMAGE_REPORT(rental_id,vehicle_id,damage_description,repair_cost,report_date,payment_status,incident_status) VALUES(1, 1, 'Scratch on rear bumper', 150.00, TO_DATE('2026-01-10','YYYY-MM-DD'), 'Pending', 'Open');
INSERT INTO DAMAGE_REPORT(rental_id,vehicle_id,damage_description,repair_cost,report_date,payment_status,incident_status) VALUES(2, 2, 'Cracked windshield caused by road debris', 680.50, TO_DATE('2026-02-05','YYYY-MM-DD'), 'Paid', 'Closed');
INSERT INTO DAMAGE_REPORT(rental_id,vehicle_id,damage_description,repair_cost,report_date,payment_status,incident_status) VALUES(3, 3, 'Dent on left front door', 120.00, TO_DATE('2026-02-18','YYYY-MM-DD'), 'Pending', 'Under Review');
INSERT INTO DAMAGE_REPORT(rental_id,vehicle_id,damage_description,repair_cost,report_date,payment_status,incident_status) VALUES(5, 4, 'Broken side mirror', 55.75, TO_DATE('2026-03-03','YYYY-MM-DD'), 'Paid', 'Resolved');
INSERT INTO DAMAGE_REPORT(rental_id,vehicle_id,damage_description,repair_cost,report_date,payment_status,incident_status) VALUES(5, 5, 'Interior upholstery stained', 10.00, TO_DATE('2026-03-20','YYYY-MM-DD'), 'Pending', 'Open');
INSERT INTO DAMAGE_REPORT(rental_id,vehicle_id,damage_description,repair_cost,report_date,payment_status,incident_status) VALUES(8, 6, 'Rear tail light broken', 110.25, TO_DATE('2026-04-07','YYYY-MM-DD'), 'Paid', 'Closed');
INSERT INTO DAMAGE_REPORT(rental_id,vehicle_id,damage_description,repair_cost,report_date,payment_status,incident_status) VALUES(1, 7, 'Front bumper damaged in parking lot', 875.00, TO_DATE('2026-04-25','YYYY-MM-DD'), 'Pending', 'Under Review');
INSERT INTO DAMAGE_REPORT(rental_id,vehicle_id,damage_description,repair_cost,report_date,payment_status,incident_status) VALUES(2, 8, 'Flat tire and damaged alloy wheel', 540.90, TO_DATE('2026-05-12','YYYY-MM-DD'), 'Paid', 'Resolved');
INSERT INTO DAMAGE_REPORT(rental_id,vehicle_id,damage_description,repair_cost,report_date,payment_status,incident_status) VALUES(3, 9, 'Deep scratches on passenger side', 395.00, TO_DATE('2026-06-01','YYYY-MM-DD'), 'Pending', 'Open');
INSERT INTO DAMAGE_REPORT(rental_id,vehicle_id,damage_description,repair_cost,report_date,payment_status,incident_status) VALUES(5, 10, 'Minor hood dent from falling object', 5.50, TO_DATE('2026-06-18','YYYY-MM-DD'), 'Paid', 'Closed');
 
INSERT INTO PROCUREMENT_RECORDS (vendor_id, manufacturer_id, vehicle_id, part_name, part_number, quantity, unit_cost, order_date, delivery_date, total_cost, status, notes) VALUES (1, 1, NULL, 'Toyota Front Brake Pad Set', '04465-02220', 10, 65.50, DATE '2026-05-12', DATE '2026-05-15', 655.00, 'Delivered', 'OEM Toyota Corolla/Matrix Front Brake Pads');
INSERT INTO PROCUREMENT_RECORDS (vendor_id, manufacturer_id, vehicle_id, part_name, part_number, quantity, unit_cost, order_date, delivery_date, total_cost, status, notes) VALUES (2, 2, NULL, 'Honda Engine Oil Filter', '15400-PLM-A02', 25, 9.50, DATE '2026-05-20', DATE '2026-05-23', 237.50, 'Delivered', 'OEM Honda Civic/CR-V Oil Filter');
INSERT INTO PROCUREMENT_RECORDS (vendor_id, manufacturer_id, vehicle_id, part_name, part_number, quantity, unit_cost, order_date, delivery_date, total_cost, status, notes) VALUES (3, 3, NULL, 'Motorcraft Tested Tough MAX Battery', 'BXT-65-850', 5, 145.00, DATE '2026-06-02', DATE '2026-06-06', 725.00, 'Delivered', 'OEM Ford/Motorcraft Group 65 Battery');
INSERT INTO PROCUREMENT_RECORDS (vendor_id, manufacturer_id, vehicle_id, part_name, part_number, quantity, unit_cost, order_date, delivery_date, total_cost, status, notes) VALUES (4, 4, NULL, 'ACDelco Gold Oil Filter', 'PF64', 30, 8.75, DATE '2026-06-15', DATE '2026-06-18', 262.50, 'Delivered', 'OEM GM/Chevrolet Oil Filter');
INSERT INTO PROCUREMENT_RECORDS (vendor_id, manufacturer_id, vehicle_id, part_name, part_number, quantity, unit_cost, order_date, delivery_date, total_cost, status, notes) VALUES (5, 5, NULL, 'BMW Engine Oil Filter Kit', '11-42-8-507-683', 15, 24.50, DATE '2026-06-25', DATE '2026-06-28', 367.50, 'Delivered', 'OEM BMW N47/N57 Oil Filter Element');
INSERT INTO PROCUREMENT_RECORDS (vendor_id, manufacturer_id, vehicle_id, part_name, part_number, quantity, unit_cost, order_date, delivery_date, total_cost, status, notes) VALUES (6, 6, NULL, 'Mercedes-Benz Oil Filter Element', '271-180-01-09', 15, 22.00, DATE '2026-07-02', DATE '2026-07-06', 330.00, 'Delivered', 'OEM Mercedes C-Class Oil Filter');
INSERT INTO PROCUREMENT_RECORDS (vendor_id, manufacturer_id, vehicle_id, part_name, part_number, quantity, unit_cost, order_date, delivery_date, total_cost, status, notes) VALUES (7, 7, NULL, 'Tesla Model 3/Y Cabin Air Filter', '1107081-00-A', 12, 28.00, DATE '2026-07-15', DATE '2026-07-20', 336.00, 'Delivered', 'OEM Tesla Cabin Air Filters');
INSERT INTO PROCUREMENT_RECORDS (vendor_id, manufacturer_id, vehicle_id, part_name, part_number, quantity, unit_cost, order_date, delivery_date, total_cost, status, notes) VALUES (8, 8, NULL, 'Hyundai Front Brake Pad Set', '58101-D3A10', 8, 72.00, DATE '2026-07-28', DATE '2026-08-10', 576.00, 'Ordered', 'OEM Hyundai Tucson Front Pads - Expected Aug 10');
INSERT INTO PROCUREMENT_RECORDS (vendor_id, manufacturer_id, vehicle_id, part_name, part_number, quantity, unit_cost, order_date, delivery_date, total_cost, status, notes) VALUES (9, 1, NULL, 'Toyota Iridium Spark Plug', '90919-01166', 24, 18.50, DATE '2026-08-01', NULL, 444.00, 'Pending', 'OEM Toyota Denso SK20R11 Spark Plugs');
INSERT INTO PROCUREMENT_RECORDS (vendor_id, manufacturer_id, vehicle_id, part_name, part_number, quantity, unit_cost, order_date, delivery_date, total_cost, status, notes) VALUES (10, 3, NULL, 'Motorcraft Mercon LV ATF', 'XT-10-QLVC', 50, 11.20, DATE '2026-08-03', NULL, 560.00, 'Cancelled', 'Order cancelled - stock unavailable');

COMMIT;

